spring:
  application:
    name: back
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#db를 파일 모드로 변경하는것 -> 영속성을 생성
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #테이블이 없을 때만 생성 되도록 재 수정